"""
License Manager for GST Reconciliation Tool
============================================
Offline, device-bound license verification system.

SECURITY ARCHITECTURE
---------------------
- Licenses are ECDSA P-256 signed JSON files (.gstlic)
- Each license encodes the target device fingerprint — it physically
  cannot activate on any other machine
- Activation state is persisted encrypted (AES-256-GCM) in %APPDATA%,
  keyed from the hardware fingerprint; copying the file to another PC
  makes decryption fail
- The private signing key is NEVER distributed; only the matching
  public key is compiled into this module
- Tampering with the activation file invalidates the GCM auth tag
  and forces re-activation

FIRST-TIME SETUP (developer)
----------------------------
1. python _license_keygen.py --setup          # generates _private_key.pem
2. Copy the printed public key into _PUB_SEGS below, replacing the
   placeholder segments
3. Keep _private_key.pem safe and SECRET — never commit or distribute it

LICENSE ISSUANCE (per customer)
--------------------------------
1. Customer runs the app → sees their Device ID (16-char hex string)
2. Customer emails Device ID to you
3. python _license_keygen.py --issue --device-id XXXX --customer "Name"
   → produces customer_license.gstlic
4. Send the .gstlic file to the customer
5. Customer opens the app → "Load License File" → selects .gstlic → Activate
"""

import os
import sys
import json
import hashlib
import base64
import struct
import ctypes
import winreg
from pathlib import Path
from datetime import date, datetime

import customtkinter as ctk
import tkinter as tk
from tkinter import filedialog, messagebox

# ── Cryptography ─────────────────────────────────────────────────────────────
try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.backends import default_backend
    from cryptography.exceptions import InvalidSignature
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    _CRYPTO_OK = True
except ImportError:
    _CRYPTO_OK = False

# ── App constants ─────────────────────────────────────────────────────────────
_APP_SALT = b"GST_RECON_GSCINTIME_2026_PROD_v1"   # unique per product line
_ACTIVATION_DIR = Path(os.path.expandvars(r"%APPDATA%\GST_Reconciliation_Tool"))
_ACTIVATION_FILE = _ACTIVATION_DIR / "activation.dat"

# ── Embedded ECDSA P-256 public key (split to resist simple text search) ──────
# Generated by: python _license_keygen.py --setup
# To replace: split the PEM body into 3 equal parts and assign below.
_PUB_SEG_A = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE"
_PUB_SEG_B = "0PqKxUzrFasDh4Ss4aDoYnz855wQHwFfZDds"
_PUB_SEG_C = "r3M4/7gNlthrrzkRFll/DnVf9QUj3E28qiriVP9kUXcnSty3fQ=="

def _get_public_key():
    """Reconstruct and load the embedded public key."""
    pem = (
        b"-----BEGIN PUBLIC KEY-----\n"
        + (_PUB_SEG_A + _PUB_SEG_B + _PUB_SEG_C).encode()
        + b"\n-----END PUBLIC KEY-----\n"
    )
    return serialization.load_pem_public_key(pem, backend=default_backend())


# ── Device fingerprinting ─────────────────────────────────────────────────────

def _reg_value(hive, path, name):
    """Read a Windows registry string value safely."""
    try:
        key = winreg.OpenKey(hive, path)
        value, _ = winreg.QueryValueEx(key, name)
        winreg.CloseKey(key)
        return str(value).strip()
    except Exception:
        return ""


def _volume_serial() -> str:
    """
    Return the C: volume serial via the Windows kernel32 API.
    Uses ctypes — no subprocess, no console, no encoding issues.
    Consistent in both normal Python and PyInstaller windowed mode.
    """
    try:
        serial = ctypes.c_uint32(0)
        ctypes.windll.kernel32.GetVolumeInformationW(
            "C:\\",
            None, 0,
            ctypes.byref(serial),
            None, None, None, 0,
        )
        return f"{serial.value:08X}"
    except Exception:
        return ""


def _raw_fingerprint():
    """
    Collect stable hardware identifiers.
    Uses only registry reads and Windows API — no subprocess,
    so the result is identical in script mode and PyInstaller windowed mode.
    """
    machine_guid = _reg_value(
        winreg.HKEY_LOCAL_MACHINE,
        r"SOFTWARE\Microsoft\Cryptography",
        "MachineGuid"
    )
    cpu_id = _reg_value(
        winreg.HKEY_LOCAL_MACHINE,
        r"HARDWARE\DESCRIPTION\System\CentralProcessor\0",
        "Identifier"        # e.g. "Intel64 Family 6 Model 158 Stepping 10"
    )
    vol_serial = _volume_serial()
    return f"{machine_guid}|{cpu_id}|{vol_serial}"


def get_device_fingerprint() -> str:
    """Return a SHA-256 hex digest of hardware identifiers + app salt."""
    raw = _raw_fingerprint()
    h = hashlib.sha256(_APP_SALT + raw.encode()).hexdigest()
    return h


def get_device_id() -> str:
    """Return the 16-char uppercase Device ID shown to users."""
    return get_device_fingerprint()[:16].upper()


# ── Activation storage (AES-256-GCM) ─────────────────────────────────────────

def _derive_aes_key(fingerprint: str) -> bytes:
    """Derive a 256-bit AES key from the device fingerprint via PBKDF2."""
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=_APP_SALT,
        iterations=200_000,
        backend=default_backend(),
    )
    return kdf.derive(fingerprint.encode())


def _save_activation(license_data: dict):
    """Encrypt and persist activation data to %APPDATA%."""
    _ACTIVATION_DIR.mkdir(parents=True, exist_ok=True)
    fingerprint = get_device_fingerprint()
    aes_key = _derive_aes_key(fingerprint)
    aesgcm = AESGCM(aes_key)
    nonce = os.urandom(12)
    plaintext = json.dumps(license_data, sort_keys=True).encode()
    ciphertext = aesgcm.encrypt(nonce, plaintext, _APP_SALT)
    with open(_ACTIVATION_FILE, "wb") as f:
        f.write(nonce + ciphertext)


def _load_activation() -> dict | None:
    """Decrypt and return activation data; returns None on any failure."""
    if not _ACTIVATION_FILE.exists():
        return None
    try:
        with open(_ACTIVATION_FILE, "rb") as f:
            data = f.read()
        if len(data) < 28:   # 12-byte nonce + 16-byte GCM tag minimum
            return None
        nonce, ciphertext = data[:12], data[12:]
        fingerprint = get_device_fingerprint()
        aes_key = _derive_aes_key(fingerprint)
        aesgcm = AESGCM(aes_key)
        plaintext = aesgcm.decrypt(nonce, ciphertext, _APP_SALT)
        return json.loads(plaintext.decode())
    except Exception:
        return None


# ── License file verification ─────────────────────────────────────────────────

def _verify_license_file(path: str) -> dict | None:
    """
    Load a .gstlic file, verify the ECDSA signature, and check that the
    device fingerprint matches.  Returns the license dict on success, None
    on any failure.
    """
    if not _CRYPTO_OK:
        messagebox.showerror(
            "Missing dependency",
            "The 'cryptography' package is not installed.\n"
            "Please contact support."
        )
        return None

    try:
        with open(path, "r", encoding="utf-8") as f:
            lic = json.load(f)
    except Exception:
        return None

    # Extract and decode signature
    try:
        sig_b64 = lic.pop("signature", None)
        if not sig_b64:
            return None
        sig = base64.b64decode(sig_b64)
    except Exception:
        return None

    # Re-create the exact payload that was signed
    payload = json.dumps(lic, sort_keys=True).encode()

    # Restore signature so the dict is complete on success
    lic["signature"] = sig_b64

    # Verify ECDSA signature
    try:
        pub_key = _get_public_key()
        pub_key.verify(sig, payload, ec.ECDSA(hashes.SHA256()))
    except (InvalidSignature, Exception):
        return None

    # Verify device binding
    expected_device_id = get_device_id()
    if lic.get("device_id", "").upper() != expected_device_id.upper():
        return None

    # Check expiry (if present)
    expires = lic.get("expires")
    if expires:
        try:
            exp_date = datetime.strptime(expires, "%Y-%m-%d").date()
            if exp_date < date.today():
                return None          # license expired
        except Exception:
            return None

    return lic


# ── Public API ────────────────────────────────────────────────────────────────

def is_activated() -> bool:
    """Return True if a valid, device-matching activation exists."""
    if not _CRYPTO_OK:
        return False
    activation = _load_activation()
    if not activation:
        return False
    # Confirm the stored device fingerprint still matches this machine
    if activation.get("device_id", "").upper() != get_device_id().upper():
        return False
    # Confirm expiry
    expires = activation.get("expires")
    if expires:
        try:
            exp_date = datetime.strptime(expires, "%Y-%m-%d").date()
            if exp_date < date.today():
                return False
        except Exception:
            return False
    return True


def activate_from_file(path: str) -> tuple[bool, str]:
    """
    Attempt to activate using a .gstlic file.
    Returns (success: bool, message: str).
    """
    lic = _verify_license_file(path)
    if lic is None:
        return False, (
            "License verification failed.\n\n"
            "Possible reasons:\n"
            "  • The license file is invalid or corrupted\n"
            "  • The license was issued for a different device\n"
            "  • The license has expired\n\n"
            "Please contact support with your Device ID."
        )
    try:
        _save_activation(lic)
        return True, f"Activation successful!\nWelcome, {lic.get('customer_name', 'User')}."
    except Exception as e:
        return False, f"Could not save activation:\n{e}"


# ── Activation dialog UI ──────────────────────────────────────────────────────

class ActivationDialog(ctk.CTkToplevel):
    """
    Modal dialog shown on first launch (or when license is invalid).
    Displays the Device ID and lets the user load a .gstlic file.
    """

    THEME_PRIMARY = "#E91E63"
    THEME_HOVER   = "#C2185B"
    THEME_LIGHT   = "#FCE4EC"
    THEME_DARK    = "#880E4F"

    def __init__(self, parent=None):
        if parent:
            super().__init__(parent)
        else:
            super().__init__()

        self.activated = False
        self._build_ui()

        self.title("Activate GST Reconciliation Tool")
        self.geometry("520x460")
        self.resizable(False, False)
        self.grab_set()
        self.lift()
        self.focus_force()
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _build_ui(self):
        device_id = get_device_id()

        # ── Header ────────────────────────────────────────────────────────────
        hdr = ctk.CTkFrame(self, fg_color=self.THEME_PRIMARY, corner_radius=0, height=64)
        hdr.pack(fill="x")
        hdr.pack_propagate(False)
        ctk.CTkLabel(
            hdr,
            text="Product Activation",
            font=ctk.CTkFont(size=20, weight="bold"),
            text_color="white",
        ).pack(expand=True)

        # ── Body ──────────────────────────────────────────────────────────────
        body = ctk.CTkFrame(self, fg_color="white", corner_radius=0)
        body.pack(fill="both", expand=True, padx=0, pady=0)

        ctk.CTkLabel(
            body,
            text="This software requires a valid license.\n"
                 "Please activate it before you can continue.",
            font=ctk.CTkFont(size=13),
            text_color="#333333",
            justify="center",
        ).pack(pady=(24, 8))

        # Device ID section
        did_frame = ctk.CTkFrame(body, fg_color=self.THEME_LIGHT, corner_radius=8)
        did_frame.pack(fill="x", padx=40, pady=8)

        ctk.CTkLabel(
            did_frame,
            text="Your Device ID  (send this to support to receive your license)",
            font=ctk.CTkFont(size=10),
            text_color="#880E4F",
        ).pack(pady=(10, 2))

        did_row = ctk.CTkFrame(did_frame, fg_color="transparent")
        did_row.pack(pady=(0, 10))

        self._did_var = tk.StringVar(value=device_id)
        did_entry = ctk.CTkEntry(
            did_row,
            textvariable=self._did_var,
            width=240,
            font=ctk.CTkFont(size=15, weight="bold"),
            state="readonly",
            justify="center",
        )
        did_entry.pack(side="left", padx=(0, 8))

        ctk.CTkButton(
            did_row,
            text="Copy",
            width=60,
            height=32,
            fg_color=self.THEME_DARK,
            hover_color=self.THEME_PRIMARY,
            command=lambda: [self.clipboard_clear(), self.clipboard_append(device_id),
                             messagebox.showinfo("Copied", "Device ID copied to clipboard.", parent=self)],
        ).pack(side="left")

        # License file section
        ctk.CTkLabel(
            body,
            text="Load your license file (.gstlic) to activate:",
            font=ctk.CTkFont(size=12),
            text_color="#555555",
        ).pack(pady=(16, 4))

        file_row = ctk.CTkFrame(body, fg_color="transparent")
        file_row.pack(padx=40, fill="x")

        self._file_var = tk.StringVar(value="No file selected")
        self._file_path = None

        file_label = ctk.CTkLabel(
            file_row,
            textvariable=self._file_var,
            font=ctk.CTkFont(size=11),
            text_color="#777777",
            anchor="w",
        )
        file_label.pack(side="left", fill="x", expand=True)

        ctk.CTkButton(
            file_row,
            text="Browse…",
            width=90,
            fg_color=self.THEME_PRIMARY,
            hover_color=self.THEME_HOVER,
            command=self._browse_license,
        ).pack(side="right")

        # Status label
        self._status_var = tk.StringVar(value="")
        self._status_label = ctk.CTkLabel(
            body,
            textvariable=self._status_var,
            font=ctk.CTkFont(size=11),
            text_color="#B71C1C",
            wraplength=420,
            justify="center",
        )
        self._status_label.pack(pady=(6, 0))

        # Activate button
        ctk.CTkButton(
            body,
            text="Activate",
            width=180,
            height=42,
            font=ctk.CTkFont(size=14, weight="bold"),
            fg_color=self.THEME_PRIMARY,
            hover_color=self.THEME_HOVER,
            command=self._do_activate,
        ).pack(pady=(12, 4))

        ctk.CTkLabel(
            body,
            text="Contact support: support@gscintime.com",
            font=ctk.CTkFont(size=10),
            text_color="#AAAAAA",
        ).pack(pady=(4, 0))

    def _browse_license(self):
        path = filedialog.askopenfilename(
            title="Select License File",
            filetypes=[("GST License", "*.gstlic"), ("All files", "*.*")],
        )
        if path:
            self._file_path = path
            self._file_var.set(os.path.basename(path))
            self._status_var.set("")

    def _do_activate(self):
        if not self._file_path:
            self._status_var.set("Please select a license file first.")
            self._status_label.configure(text_color="#B71C1C")
            return
        success, msg = activate_from_file(self._file_path)
        if success:
            self._status_var.set(msg)
            self._status_label.configure(text_color="#2E7D32")
            self.activated = True
            self.after(1800, self.destroy)
        else:
            self._status_var.set(msg)
            self._status_label.configure(text_color="#B71C1C")

    def _on_close(self):
        """Closing the dialog without activating exits the app."""
        self.activated = False
        self.destroy()


def require_license(parent=None) -> bool:
    """
    Call this at application startup.
    Returns True if the app is licensed and may continue.
    Returns False if the user closed the dialog without activating
    (caller should sys.exit()).
    """
    if not _CRYPTO_OK:
        messagebox.showerror(
            "Startup Error",
            "A required security component is missing.\n"
            "Please reinstall the application or contact support."
        )
        return False

    if is_activated():
        return True

    dlg = ActivationDialog(parent)
    if parent:
        parent.wait_window(dlg)
    else:
        dlg.mainloop()

    return dlg.activated


# ── YTD Credentials ───────────────────────────────────────────────────────────
_CREDS_FILE = _ACTIVATION_DIR / "ytd_creds.dat"


def has_ytd_credentials() -> bool:
    """Return True if YTD credentials have been set up."""
    return _CREDS_FILE.exists()


def save_ytd_credentials(username: str, password: str):
    """Save YTD credentials (username + salted SHA-256 hash of password)."""
    import secrets as _sec
    _ACTIVATION_DIR.mkdir(parents=True, exist_ok=True)
    salt = _sec.token_hex(32)
    pwd_hash = hashlib.sha256(f"{salt}:{password}".encode()).hexdigest()
    creds = {"username": username.strip(), "salt": salt, "password_hash": pwd_hash}
    with open(_CREDS_FILE, 'w', encoding='utf-8') as f:
        json.dump(creds, f)


def verify_ytd_credentials(username: str, password: str) -> bool:
    """Return True if username+password match the stored credentials."""
    if not _CREDS_FILE.exists():
        return False
    try:
        with open(_CREDS_FILE, encoding='utf-8') as f:
            creds = json.load(f)
        stored_hash = hashlib.sha256(f"{creds['salt']}:{password}".encode()).hexdigest()
        return (username.strip() == creds.get('username', '') and
                stored_hash == creds.get('password_hash', ''))
    except Exception:
        return False


def get_ytd_username() -> str:
    """Return the stored YTD username, or empty string."""
    try:
        with open(_CREDS_FILE, encoding='utf-8') as f:
            return json.load(f).get('username', '')
    except Exception:
        return ''
